"""added last updated

Revision ID: 85a51f4152ee
Revises: 
Create Date: 2020-06-15 12:39:51.237034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a51f4152ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('last_updated_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_packages_last_updated_date'), 'packages', ['last_updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_last_updated_date'), table_name='packages')
    op.drop_column('packages', 'last_updated_date')
    # ### end Alembic commands ###
